version: "3"
services:
  web:
    image: "controlly"
    build: .
    ports:
      - "3000:3000"
    labels:
      kompose.service.type: LoadBalancer
    volumes:
      - .:/home/node/src
      - /home/node/src/node_modules
    # links:
    #   # -db
    # environment:
    #   # envVariable:""
